### ISSUE TITLE
wallet version 3.1.0.1 sync error

### ISSUE THREAD

**Issue by card1001** [TheLindaProjectInc/Metrix#11]
In version 3.1.0.1 wallet # 476204th block is not synchronized.

So I have to sync with a lower version wallet and have to reload the version again.

**Comment by davidstoneham** [comment]
@card1001 thanks for bringing this to our attention. We'll investigate the issue

**Comment by jrkenn** [comment]
I am also having this problem. I updated with the bootstrap to speed up the sync and added the nodes but when it got to 476204 it just doesnt go any further

**Comment by jrkenn** [comment]
Use this bootstrap repository and it will fix the sync in 3.1.0.1
https://www.dropbox.com/sh/0s9apwcl0uhlpmy/AABysrq0PEosSaHQKGyxCTioa

The other bootstrap I used did not work but this one put me at two weeks behind and had me updated within a couple of minutes.

**Comment by davidstoneham** [comment]
This is now resolved in the latest release
