### ISSUE TITLE
MacOSX version v3.1.0.1 runs slow even after bootstrapping

### ISSUE THREAD

**Issue by ckhatton** [TheLindaProjectInc/Metrix#12]
Is there any reason why the MacOSX qt wallet syncs slowly and hangs multiples times, compared to the Win64 qt wallet? It can never keep up with the latest block, unless the bootstrap file happens to be super fresh off the cooker.

I have witnessed this on previous versions of the wallet as well, so it's not a recent issue.

OpenSSL version: 1.0.2g  1 Mar 2016

Does that come packaged with the qt wallet? As my OpenSSL version is higher than that!

:octocat:

**Comment by davidstoneham** [comment]
OpenSSL comes pre-packaged with the app to ensure compatibility. The next release contains many performance improvements which should address the issue you are describing.
In the interim, you can switch to the current dev branch which is nearing a release candidate or try the following steps:
If your peers are above 100 try lowering the max peers Lindad can use
inspect your debug.log file to see if Linda is processing lost or orphan blocks. if it is, try setting `maxorphanblocks` to ~300 and obtaining a new peers.dat file from the linda bootstrap to remove misbehaving peers you may have

**Comment by ckhatton** [comment]
Okay great, I don't mind trying out the dev branch but how would one package it for macOS?

The peers usually sits around 30.

**Comment by ckhatton** [comment]
Anyway you can help direct me to how to build it for macOS @davidstoneham? The macOS version is proving a pain now; I don't know if it is because I am running on 10.14, but I have to wait until the bootstrap is current for the wallet to be in sync. As I understand it, the bootstrap files are updated every 6 hours.

**Comment by davidstoneham** [comment]
@ckhatton the dev branch isn't completely tested so I can't recommend changing to this branch. If your wallet is having issues keep up once it has synced this sounds more like an issue isolated to your machine. If you could post the last few lines of your debug.log when your computer is having issues so we can see if it's an issue with your peers.

**Comment by ckhatton** [comment]
Okay sure, will do!

**Comment by davidstoneham** [comment]
This is now resolved in the latest release
