### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by brmmm3** [TheLindaProjectInc/Metrix#176]
I've downloaded the latest master branch.
Compilation fails here:
In file included from ./qtum/qtumstate.h:10,
                 from ./validation.h:41,
                 from bench/block_assemble.cpp:11:
./qtum/qtumtransaction.h: In static member function ‘static VersionVM VersionVM::fromRaw(uint32_t)’:
./qtum/qtumtransaction.h:24:24: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   24 |         VersionVM x = *(VersionVM*)&val;
      |                        ^~~~~~~~~~~~~~~~
./qtum/qtumtransaction.h:24:24: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
In file included from ./qtum/qtumstate.h:10,
                 from ./validation.h:41,
                 from bench/checkblock.cpp:9:
./qtum/qtumtransaction.h: In static member function ‘static VersionVM VersionVM::fromRaw(uint32_t)’:
./qtum/qtumtransaction.h:24:24: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   24 |         VersionVM x = *(VersionVM*)&val;
      |                        ^~~~~~~~~~~~~~~~
./qtum/qtumtransaction.h:24:24: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
In file included from /usr/include/c++/9/tuple:39,
                 from /usr/include/c++/9/functional:54,
                 from ./bench/bench.h:8,
                 from bench/block_assemble.cpp:5:
/usr/include/c++/9/array: In instantiation of ‘struct std::__array_traits<std::shared_ptr<const CTransaction>, 18446744073709551257>’:
/usr/include/c++/9/array:110:56:   required from ‘struct std::array<std::shared_ptr<const CTransaction>, 18446744073709551257>’
bench/block_assemble.cpp:30:69:   required from here
/usr/include/c++/9/array:50:19: error: size ‘18446744073709551257’ of array exceeds maximum object size ‘9223372036854775807’
   50 |       typedef _Tp _Type[_Nm];
      |                   ^~~~~

**Comment by nibbles83** [comment]
What OS is this on? Did you clone the repo using the --recursive flag?

**Comment by nibbles83** [comment]
Will close this as dead issue. If you are still getting issue compiling please feel free to update the comments.
