### ISSUE TITLE
Typical bugs when running deamon as masternode on ubuntu or debian server

### ISSUE THREAD

**Issue by MeisterOT** [TheLindaProjectInc/Metrix#30]
Exemplary tested on 18.04. ubuntu VPS
 "version" : "v3.1.0.0-g",
    "protocolversion" : 70000,

Lindad getinfo shows these THREE typical errors:

1.  `Lindad getinfo` shows `errors: "EXCEPTION... "`
short after it shows beahaviour below or crashes completly and need to start again.

2. Lindad hangs / crashes but is still visible `htop` with SHRvalue of `ZERO [0]` and TIME+ up to `12h`
![lindad-timedelay](https://user-images.githubusercontent.com/43780758/48310240-fa753400-e58b-11e8-8b3b-7df027e74416.JPG)
Can only be solved by killing the deamon before restarting it.

3. Lindad block sync hangs and only stopping of deamon, bootsrapping and restart helps to get it in sync again

During all the three errors CPU consumption is often around 100% all the time!

If different rootscauses are investigated by the DEV's plz split this issues into 3 single ones...

**Comment by davidstoneham** [comment]
Issue 1. Would you be able to send the entire error and the debug.log output when the error occurs? With no way to replicate the issue we won't be able to investigate the problem.

I suspect issues 2 and 3 are both the result of the slow db engine linda uses which can cause lockups in the program during syncing. The next release has a major overhaul to this system and should solve these issues.

Please also include how to reproduce these problems, with just the outline of the problem it is very difficult for us to deduce the issue in the software or if it is isolated to your setup

**Comment by ckhatton** [comment]
Issues 2 and 3 are what I am experiencing on macOS.

**Comment by MeisterOT** [comment]
Thy @davidstoneham AND @ckhatton (I talked about Lindad NOT Linda-QT) for quick reaction.

Issue 2 & 3:

- When version with new database will be available approx.?

Issue 1:

- Would have already support you, but activated `coredumpctl` writes sometimes no logs for Lindad when it occurs... and in the few cases it did, file was only saved too short, so I missed it!

- Where else to find a debug.log OR any idea how to make ubuntu 18.04 to save one OR configure coredump to save the logs longer?

![coredumplist_lindad_head](https://user-images.githubusercontent.com/43780758/48507918-82d62c00-e84d-11e8-975b-becd3eb12256.JPG)
![coredumplist_lindad-0](https://user-images.githubusercontent.com/43780758/48508021-c6c93100-e84d-11e8-8e26-3fc30e3dda40.JPG)
![coredumplist_lindad](https://user-images.githubusercontent.com/43780758/48507732-07747a80-e84d-11e8-9c37-e78d77a7acde.JPG)

**Comment by davidstoneham** [comment]
On Linux you can find logs under the Linda data directory. Typically ~/.Linda/debug.log

**Comment by ckhatton** [comment]
@MeisterOT Yeh I know... I just wanted to make sure everyone was super clear on the fact that the macOS version is super hangy and crashy as well 😅

**Comment by davidstoneham** [comment]
These issues should be resolved in the latest release
