### ISSUE TITLE
error loading block database

### ISSUE THREAD

**Issue by harrizyo408** [TheLindaProjectInc/Metrix#4]
there is an error loading block database on the linda qt wallet

**Comment by davidstoneham** [comment]
Unfortunately, this is an issue with a corrupt database. You will have to re-sync your block chain to solve this. The easiest way to do this would be to download the bootstrap. If you need help bootstrapping the block chain then jump on the discord or grab one of the guides on the website

**Comment by BraapAround** [comment]
@harrizyo408 Join our discord: https://discord.gg/SHNjQBv and please close this issue.
